#FROM openjdk:8-jre
#ADD SimpleHelloWorldAPI/target/*.jar app.jar
#EXPOSE 9012
#ENTRYPOINT [ "java","-jar","app.jar"]

FROM openjdk:8-jre
ADD target/*.jar app.jar
EXPOSE 9012
ENTRYPOINT [ "java","-jar","app.jar"]
